"""
Custom configs for each model.
"""

import numpy as np
from detectron2.config import CfgNode as CN

def add_deformable_detr_config(cfg):
    cfg.SOLVER.CHECKPOINT_PERIOD = None
    
    cfg.MODEL.DEFORMABLE_DETR = CN()
    cfg.MODEL.DEFORMABLE_DETR.NUM_CLASSES = None
    
    # Solver
    cfg.SOLVER.BACKBONE_LR_MULTIPLIER = None
    cfg.SOLVER.LR_BACKBONE_NAMES = None
    cfg.SOLVER.LR_LINEAR_PROJ_NAMES = None
    cfg.SOLVER.LR_LINEAR_PROJ_MULTIPLIER = None
    cfg.SOLVER.OPTIMIZER = None

    # Variants of Deformable DETR
    cfg.MODEL.DEFORMABLE_DETR.WITH_BOX_REFINE = None
    cfg.MODEL.DEFORMABLE_DETR.TWO_STAGE = None

    # For segmentation
    cfg.MODEL.DEFORMABLE_DETR.FROZEN_WEIGHTS = None

    # Backbone
    cfg.MODEL.DEFORMABLE_DETR.BACKBONE = None
    cfg.MODEL.DEFORMABLE_DETR.DILATION = None
    cfg.MODEL.DEFORMABLE_DETR.POSITION_EMBEDDING = None
    cfg.MODEL.DEFORMABLE_DETR.POSITION_EMBEDDING_SCALE = None
    cfg.MODEL.DEFORMABLE_DETR.NUM_FEATURE_LEVELS = None

    # Transformer
    cfg.MODEL.DEFORMABLE_DETR.TRANSFORMER = CN()
    cfg.MODEL.DEFORMABLE_DETR.TRANSFORMER.NUM_QUERIES = None
    cfg.MODEL.DEFORMABLE_DETR.TRANSFORMER.ENC_LAYERS = None
    cfg.MODEL.DEFORMABLE_DETR.TRANSFORMER.DEC_LAYERS = None
    cfg.MODEL.DEFORMABLE_DETR.TRANSFORMER.NHEADS =  None
    cfg.MODEL.DEFORMABLE_DETR.TRANSFORMER.DIM_FEEDFORWARD = None
    cfg.MODEL.DEFORMABLE_DETR.TRANSFORMER.HIDDEN_DIM = None
    cfg.MODEL.DEFORMABLE_DETR.TRANSFORMER.DROPOUT = None
    cfg.MODEL.DEFORMABLE_DETR.TRANSFORMER.DEC_N_POINTS = None
    cfg.MODEL.DEFORMABLE_DETR.TRANSFORMER.ENC_N_POINTS = None

    # Loss
    cfg.MODEL.DEFORMABLE_DETR.LOSS = CN()
    cfg.MODEL.DEFORMABLE_DETR.LOSS.AUX_LOSS = None
    cfg.MODEL.DEFORMABLE_DETR.LOSS.MASK_LOSS_COEF = None
    cfg.MODEL.DEFORMABLE_DETR.LOSS.DICE_LOSS_COEF = None
    cfg.MODEL.DEFORMABLE_DETR.LOSS.CLS_LOSS_COEF = None
    cfg.MODEL.DEFORMABLE_DETR.LOSS.BBOX_LOSS_COEF = None
    cfg.MODEL.DEFORMABLE_DETR.LOSS.GIOU_LOSS_COEF = None
    cfg.MODEL.DEFORMABLE_DETR.LOSS.FOCAL_ALPHA = None

    # Matcher
    cfg.MODEL.DEFORMABLE_DETR.MATCHER = CN()
    cfg.MODEL.DEFORMABLE_DETR.MATCHER.SET_COST_CLASS = None
    cfg.MODEL.DEFORMABLE_DETR.MATCHER.SET_COST_BBOX = None
    cfg.MODEL.DEFORMABLE_DETR.MATCHER.SET_COST_GIOU = None
