_BASE_: "deformable_detr_base.yaml"

SEED: 42
OUTPUT_DIR: 'saved/deformable_detr_r50'

MODEL:
  DEFORMABLE_DETR:
    NUM_CLASSES: 80
    BACKBONE: 'resnet50'
    DILATION: False
    POSITION_EMBEDDING: 'sine' # sine or learned
    POSITION_EMBEDDING_SCALE: 6.283185307179586 # 2*np.pi
    NUM_FEATURE_LEVELS: 4
    # Variants of Deformable DETR
    WITH_BOX_REFINE: False
    TWO_STAGE: False
    TRANSFORMER:
      NUM_QUERIES: 300
      ENC_LAYERS: 6
      DEC_LAYERS: 6
      NHEADS: 8
      DIM_FEEDFORWARD: 1024
      HIDDEN_DIM: 256
      DROPOUT: 0.1
      DEC_N_POINTS: 4
      ENC_N_POINTS: 4
    LOSS:
      AUX_LOSS: True
      MASK_LOSS_COEF: 1.0
      DICE_LOSS_COEF: 1.0
      CLS_LOSS_COEF: 2.0
      BBOX_LOSS_COEF: 5.0
      GIOU_LOSS_COEF: 2.0
      FOCAL_ALPHA: 0.25
    MATCHER:
      SET_COST_CLASS: 2
      SET_COST_BBOX: 5
      SET_COST_GIOU: 2
    FROZEN_WEIGHTS: False # For segmentation
  MASK_ON: False

SOLVER:
  IMS_PER_BATCH: 16 # warning: change MAX_ITER, STEPS, BASE_LR if you change this
  BASE_LR: 1e-4 # 2e-4 for bs of 32
  BACKBONE_LR_MULTIPLIER: 0.1
  LR_BACKBONE_NAMES: ["backbone.0"]
  LR_LINEAR_PROJ_NAMES: ['reference_points', 'sampling_offsets']
  LR_LINEAR_PROJ_MULTIPLIER: 0.1
  OPTIMIZER: "ADAMW"
  MAX_ITER: 368750 # 50 epochs on COCO train 2017: 50 * (118000 // SOLVER.IMS_PER_BATCH)
  STEPS: (295000,) # 40 epochs on COCO train 2017: (40 * (118000 // SOLVER.IMS_PER_BATCH),)
  CHECKPOINT_PERIOD: 50000

TEST:
  DETECTIONS_PER_IMAGE: 100 # 100 for COCO
  EVAL_PERIOD: 50000
